### PR TITLE
Update timings

### LINKED ISSUE #28: Expand functions timed for benchmarks
It would be great to benchmark the performance of other aspects of FTorch, such as the setup, deletion etc. of the models, in addition to the inference we currently time.

### PR DESCRIPTION
**Pull request by ElliottKasoar**
Resolves #28

Added timings for essentially all non-shared functions in the three main benchmark scripts.

These could be separated further, but currently it is split into:
- Module operations (loading/deleting the model)
- Tensor operations (creating/deleting tensors/arrays)
- Inference operations (forward pass, already being timed)

This also includes a new function to print a combined mean of the above timings.

### CODE REVIEW

**Comment by ElliottKasoar** [comment]
Note: The last commit undoes a change introduced earlier to try to generalise the reading of TorchScript for forpy. However, since forpy also requires the python module name, we would need an additional input (or to do something like pattern-match the module name from the `.pt` file, which we cannot currently do in a consistent way).

I've reverted back to hardcoded `.pt` file names for now, and suggest we revisit if we decide we want to run forpy on GPUs (in which case, we can create a new PR), as until then, I don't think it's a significant problem.

**Review by jatkinson1000 — COMMENTED** [review]
This is fantastic work @ElliottKasoar, particularly the visualisation of results!

The convergence of the timings towards the end of the runs is particularly interesting. Were these examples run on a local machine rather than CSD3?
We should have a meeting to look at these in detail.

- Personally I wouldn't have written in the `call main()` format, but I don't see anything wrong with doing so.
- Also (you may already be aware that) `implicit none` in a program or module applies to all scoping units so isn't necessary in all functions or subroutines. One may argue that it is good practice, however, as it does no harm and ensures all bases are covered.

I have left this review as a 'comment' and will let @TomMelt have final say as he has perhaps been more closely associated with this part of the work.

**Comment by ElliottKasoar** [comment]
> This is fantastic work @ElliottKasoar, particularly the visualisation of results!
> 
> The convergence of the timings towards the end of the runs is particularly interesting. Were these examples run on a local machine rather than CSD3? We should have a meeting to look at these in detail.
 
Thanks @jatkinson1000! Yep, unfortunately the notebook only has local results so far, so we probably can't look too far into the distribution of these results, it's mostly illustrative. I'm trying to get some numbers from CSD3 today, so hopefully we can get a better look soon.

>     * Personally I wouldn't have written in the `call main()` format, but I don't see anything wrong with doing so.

I think I originally added it partly as an option to make it neater if we wanted to time the entire program, but I also thought it might make a bit more sense now that we're factoring out more code into subroutines, to limit any scope creep. Is there anything in particular behind your preference?

>     * Also (you may already be aware that) `implicit none` in a program or module applies to all scoping units so isn't necessary in all functions or subroutines. One may argue that it is good practice, however, as it does no harm and ensures all bases are covered.

Ah interesting, thanks. I had a feeling that might be the case, but I wasn't sure. I guess it can help clarify that it still applies, particularly for longer programs.

**Comment by jatkinson1000** [comment]
> Is there anything in particular behind your preference?

Not at all! Hence happy to leave as is.
Indeed there are some people who prefer this approach in python with:
```python3
if __name__ == "__main__":
    main()
``` 


> Ah interesting, thanks. I had a feeling that might be the case, but I wasn't sure. I guess it can help clarify that it still applies, particularly for longer programs.

Yes, it's not necessarily a bad thing to be extra safe!

**Review by TomMelt — COMMENTED** [review]
Thanks @ElliottKasoar, looks good to me. Only comment is should we delete the output from `utils/visualise.ipynb` before saving it to github?

**Comment by ElliottKasoar** [comment]
> Thanks @ElliottKasoar, looks good to me. Only comment is should we delete the output from `utils/visualise.ipynb` before saving it to github?

I definitely agree it becomes messy if we were to frequently change the outputs.

My general experience is that it can be nice to have an example of the cell outputs, and it all displays quite nicely on GitHub.

You could argue that we ought to "finalise" the functions/notebook with the more complete data (e.g. to show all the plots we discussed as the main CSD3 results), so definitely to delete it too (for now, or permanently).

I think there's also an intermediate option where you can keep the main outputs, but remove a lot of the metadata, although I think that requires installing extra dependencies e.g. nbconvert, so I've never felt it's worth it in the past.

**Comment by TomMelt** [comment]
Ok I keep forgetting this is the benchmark repo and not the Ftorch lib. So I think for this repo it is perfectly reasonable to keep the plots for now. So I will accepts this PR and merge the branch.

**Pull request merged**
