### PR TITLE
Tidy repo

### LINKED ISSUE #24: Tidy benchmarking
A general pass of the repo is needed to tidy up, potentially including:

- [x] Ensuring all unused variables are removed/used
- [x] Add functioning assertions to all benchmarks
- [x] Remove code that is no longer needed (#18?)
- [x] Refactor shared code (e.g. between assert functions in #22)
- [x] Ensure changes in FTorch are reflected in code here
- [x] Restructure code into separate folders, as mentioned in #20

### PR DESCRIPTION
**Pull request by ElliottKasoar**
Resolves #24

Initial work tidying repository, so far including:

- Creating separate directories) for each benchmark code, and for each model with its data
  - I kept the model directories separate to the benchmark directories, as the models may be shared between different benchmark codes, as is the case for cgdrag/MiMA, but it might be tidier to have them in the same directory?
- General tidy up of white space etc.
- Adding new assert to interface to update cgdrag's assertions

### CODE REVIEW

**Comment by ElliottKasoar** [comment]
@jatkinson1000, there are a couple of unused variables/functions in the MiMA codes e.g. [level](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/ff78db97be760dc8351aa4d68b4cfdaa63f9b3db/benchmark_mima/cg_drag_forpy_mod.f90#L47), [error_mesg](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/ff78db97be760dc8351aa4d68b4cfdaa63f9b3db/benchmark_mima/cg_drag_torch_mod.f90#L39). Is it ok to remove them or do we want to keep these to keep this code as close as possible to the original implementation?

**Comment by jatkinson1000** [comment]
No, fine to remove I think.
If unused won't make a difference.
It's not actually in the original [here](https://github.com/DataWaveProject/MiMA-machine-learning/blob/pytorch/src/atmos_param/cg_drag/pytorch.f90) so not sure how/why it got there...

**Comment by ElliottKasoar** [comment]
Discussed at various stages with @TomMelt, but the general logic behind the changes to real definitions, which are the most substantial changes made in this PR, is:

- In general, I've tried to use `wp` where sensible for data that interacts with the model. `dp` is used explicitly for the timings (even when `wp=dp`), as there's no need for them to match in general.
- It's slightly messy, but I set `wp=dp` for cgdrag and MiMA, to allow the saved models to run as is, while maintaining the same style of `wp` for variables that in principle we may want to change the precision of together.
- There is potentially room to tidy up the assert subroutines further, either by:
  - Changing the cgdrag/MiMA benchmarks to `sp` (or the large_stride and resnet benchmarks to `dp`), such that they all share the same `wp`. This would allow the utils asserts to all use the same `wp`, but would require non-trivial changes, including updating the saved model(s), data types in various places etc.
  - Implementing templating or other methods to define the subroutines for different multiple kinds (see: https://github.com/fortran-lang/stdlib/issues/35, which references an example of the use of [fypp](https://github.com/jvdp1/stdlib/blob/38ebf87d8d6512a06e55f2605c338aece84216da/src/stdlib_experimental_io.fypp#L35))

**Comment by TomMelt** [comment]
@ElliottKasoar `fypp` looks like a good solution for the `wp=sp,dp...` problem.

**Review by TomMelt — APPROVED** [review]
Thanks @ElliottKasoar. These are some really good improvements.

**Comment by TomMelt** [comment]
> Is the comment I added enough to close #2?

Hard to say. I am not 100% sure. But I think it would refer to people who maybe use their distro shipped version of python. On Ubuntu, for example, you need to install dev packages separately. Something like `sudo apt install python-dev`. @SimonClifford is this what you were referring too?

**Comment by ElliottKasoar** [comment]
> > Is the comment I added enough to close #2?
> 
> Hard to say. I am not 100% sure. But I think it would refer to people who maybe use their distro shipped version of python. On Ubuntu, for example, you need to install dev packages separately. Something like `sudo apt install python-dev`. @SimonClifford is this what you were referring too?

I certainly encountered an error before installing python-dev on Ubuntu, which I was hoping could be inferred from the comment, but I thought it might be best to keep the comment slightly more general, as I imagine there could be similar requirements on a different distribution/OS.

**Pull request merged**
